"""Pure ASGI middleware applied outside FastAPI's framework stack."""

import posixpath

# _utils is private, but get_route_path is the exact function FastAPI's router
# and StaticFiles use to remove root_path before matching. Importing it from
# the defining module (rather than starlette.routing's implicit re-export)
# keeps strict typing sound and ensures these checks evolve with the router.
from starlette._utils import get_route_path
from starlette.datastructures import Headers, MutableHeaders
from starlette.exceptions import HTTPException as StarletteHTTPException
from starlette.responses import JSONResponse
from starlette.types import ASGIApp, Message, Receive, Scope, Send

SECURITY_HEADERS = {
    "Content-Security-Policy": (
        "default-src 'none'; "
        "script-src 'self'; "
        "style-src 'self'; "
        "img-src 'self'; "
        "connect-src 'self'; "
        "base-uri 'none'; "
        "form-action 'self'; "
        "frame-ancestors 'none'"
    ),
    "X-Content-Type-Options": "nosniff",
    "X-Frame-Options": "DENY",
    "Referrer-Policy": "strict-origin-when-cross-origin",
    "Cross-Origin-Opener-Policy": "same-origin",
    "Cross-Origin-Resource-Policy": "same-origin",
    "Permissions-Policy": "camera=(), microphone=(), geolocation=()",
}
# HSTS intentionally belongs at the TLS-terminating reverse proxy; this app
# speaks plain HTTP and should not guess how it is exposed.

# FastAPI's generated docs use CDN scripts/styles, inline bootstrapping and
# data images. Keep those exceptions scoped to the docs subtree.
DOCS_CSP = (
    SECURITY_HEADERS["Content-Security-Policy"]
    .replace(
        "script-src 'self'",
        "script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net",
    )
    .replace(
        "style-src 'self'",
        "style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net",
    )
    .replace(
        "connect-src 'self'",
        "connect-src 'self' https://cdn.jsdelivr.net",
    )
    .replace("img-src 'self'", "img-src 'self' data: https://fastapi.tiangolo.com")
)


class SecurityHeadersMiddleware:
    """
    Stamp hardening headers on every HTTP response.

    This wrapper belongs outside FastAPI so even responses generated by its
    outer ``ServerErrorMiddleware`` receive the headers. When docs are enabled,
    only the docs subtree receives the narrowly relaxed CSP.
    """

    def __init__(self, app: ASGIApp, *, docs_enabled: bool) -> None:
        """Wrap ``app`` and configure whether the docs policy can be used."""
        self.app = app
        self.docs_enabled = docs_enabled

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] != "http":
            await self.app(scope, receive, send)
            return

        # Normalize after removing root_path: StaticFiles serves the normalized
        # target, and FastAPI matches against the root-path-relative route.
        path = posixpath.normpath(get_route_path(scope))
        is_docs = self.docs_enabled and (path == "/docs" or path.startswith("/docs/"))

        async def send_with_headers(message: Message) -> None:
            if message["type"] == "http.response.start":
                headers = MutableHeaders(scope=message)
                headers.update(SECURITY_HEADERS)
                if is_docs:
                    headers["Content-Security-Policy"] = DOCS_CSP
            await send(message)

        await self.app(scope, receive, send_with_headers)


class BodySizeLimitMiddleware:
    """
    Reject request bodies that exceed an application-level byte limit.

    Declared sizes are rejected before routing; streamed bodies are counted as
    the downstream endpoint consumes them. A reverse proxy should enforce the
    same limit to cover streams sent to endpoints that never read a body.
    """

    def __init__(self, app: ASGIApp, *, max_body_bytes: int) -> None:
        """Wrap ``app`` with a maximum request-body size."""
        self.app = app
        self.max_body_bytes = max_body_bytes

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] != "http":
            await self.app(scope, receive, send)
            return

        # Uvicorn's HTTP parser has already validated Content-Length as an int.
        declared = Headers(scope=scope).get("content-length")
        if declared is not None and int(declared) > self.max_body_bytes:
            response = JSONResponse(
                {"detail": f"Request body exceeds {self.max_body_bytes} bytes"},
                status_code=413,
            )
            await response(scope, receive, send)
            return

        received = 0

        async def guarded_receive() -> Message:
            nonlocal received
            message = await receive()
            if message["type"] == "http.request":
                received += len(message.get("body", b""))
                if received > self.max_body_bytes:
                    raise StarletteHTTPException(
                        413,
                        detail=(f"Request body exceeds {self.max_body_bytes} bytes"),
                    )
            return message

        await self.app(scope, guarded_receive, send)
