"""ASGI middleware wrapping FastAPI's stack, plus the host guard inside it."""

import posixpath
from collections.abc import Iterable

# _utils is private, but get_route_path is the exact function FastAPI's router
# and StaticFiles use to remove root_path before matching. Importing it from
# the defining module (rather than starlette.routing's implicit re-export)
# keeps strict typing sound and ensures these checks evolve with the router.
from starlette._utils import get_route_path
from starlette.datastructures import Headers, MutableHeaders
from starlette.exceptions import HTTPException as StarletteHTTPException
from starlette.middleware.trustedhost import TrustedHostMiddleware
from starlette.responses import JSONResponse
from starlette.types import ASGIApp, Message, Receive, Scope, Send

from .observability import REQUEST_ID_HEADER, bind_request_id

SECURITY_HEADERS = {
    "Content-Security-Policy": (
        "default-src 'none'; "
        "script-src 'self'; "
        "style-src 'self'; "
        "img-src 'self'; "
        "connect-src 'self'; "
        "base-uri 'none'; "
        "form-action 'self'; "
        "frame-ancestors 'none'"
    ),
    "X-Content-Type-Options": "nosniff",
    "X-Frame-Options": "DENY",
    "Referrer-Policy": "strict-origin-when-cross-origin",
    "Cross-Origin-Opener-Policy": "same-origin",
    "Cross-Origin-Resource-Policy": "same-origin",
    "Permissions-Policy": "camera=(), microphone=(), geolocation=()",
}
# HSTS intentionally belongs at the TLS-terminating reverse proxy; this app
# speaks plain HTTP and should not guess how it is exposed.

# FastAPI's generated docs use CDN scripts/styles, inline bootstrapping and
# data images. Keep those exceptions scoped to the docs subtree.
DOCS_CSP = (
    SECURITY_HEADERS["Content-Security-Policy"]
    .replace(
        "script-src 'self'",
        "script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net",
    )
    .replace(
        "style-src 'self'",
        "style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net",
    )
    .replace(
        "connect-src 'self'",
        "connect-src 'self' https://cdn.jsdelivr.net",
    )
    .replace("img-src 'self'", "img-src 'self' data: https://fastapi.tiangolo.com")
)

# Swagger UI's OAuth flow opens a cross-origin identity provider in a popup,
# which ultimately returns to /docs/oauth2-redirect and communicates through
# window.opener. The strict default severs that relationship as soon as the
# popup crosses origins; this value preserves it without relaxing other pages.
DOCS_COOP = "same-origin-allow-popups"


class RequestIDMiddleware:
    """
    Give every request a correlation ID, in the logs and on the response.

    Outermost by design: the ID has to exist before anything below can log or
    answer, so a body-cap 413, a rejected ``Host``, an unhandled exception's
    500 - responses produced without an endpoint ever running - are all
    findable in the log by the same ID the client was handed back.

    Echoing the header is what makes the ID reachable without log access: a
    user reporting a failure can read it off the response, and a caller can
    attach it to a bug report or pass it to the next service.
    """

    def __init__(self, app: ASGIApp) -> None:
        """Wrap ``app`` so its requests are correlated."""
        self.app = app

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] != "http":
            await self.app(scope, receive, send)
            return

        with bind_request_id(Headers(scope=scope).get(REQUEST_ID_HEADER)) as request_id:

            async def send_with_request_id(message: Message) -> None:
                if message["type"] == "http.response.start":
                    MutableHeaders(scope=message)[REQUEST_ID_HEADER] = request_id
                await send(message)

            # Inside the binding, which is what puts the ID on uvicorn's
            # access line: uvicorn logs it from the send() call above, i.e.
            # still within this request's context.
            await self.app(scope, receive, send_with_request_id)


class SecurityHeadersMiddleware:
    """
    Stamp hardening headers on every HTTP response.

    This wrapper belongs outside FastAPI so even responses generated by its
    outer ``ServerErrorMiddleware`` receive the headers. When docs are enabled,
    only the docs subtree receives narrowly relaxed browser policies.
    """

    def __init__(self, app: ASGIApp, *, docs_enabled: bool) -> None:
        """Wrap ``app`` and configure whether the docs policy can be used."""
        self.app = app
        self.docs_enabled = docs_enabled

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] != "http":
            await self.app(scope, receive, send)
            return

        # Normalize after removing root_path: StaticFiles serves the normalized
        # target, and FastAPI matches against the root-path-relative route.
        # Raw clients need not resolve dot segments the way browsers do, so a
        # raw /docs/../css/theme.css is a real asset that must keep the strict
        # policies, never the docs relaxations.
        path = posixpath.normpath(get_route_path(scope))
        is_docs = self.docs_enabled and (path == "/docs" or path.startswith("/docs/"))

        async def send_with_headers(message: Message) -> None:
            if message["type"] == "http.response.start":
                headers = MutableHeaders(scope=message)
                headers.update(SECURITY_HEADERS)
                if is_docs:
                    headers["Content-Security-Policy"] = DOCS_CSP
                    headers["Cross-Origin-Opener-Policy"] = DOCS_COOP
            await send(message)

        await self.app(scope, receive, send_with_headers)


class HostValidationMiddleware:
    """
    Enforce the ``Host`` allowlist, except on paths that answer without one.

    Starlette's ``TrustedHostMiddleware`` still does the matching - wildcards,
    the ``"*"`` opt-out, the 400 - and this wrapper only decides which
    requests reach it. The exemption exists for orchestrator probes: a
    Kubernetes ``httpGet`` probe sends the pod's own IP as ``Host``, an
    address no allowlist can name in advance, so a guarded probe route makes
    every deployment fail its own liveness check and restart forever. A path
    listed here must therefore answer without ever putting ``Host`` into a
    response - see "Trusted hosts" in docs/ARCHITECTURE.md.

    Paths are compared exactly, after ``root_path`` is removed and
    *without* normalizing - the opposite of the CSP check above, because here
    normalizing would *widen* the exemption rather than narrow a relaxation.
    ``/livez/`` normalizes onto the exempt path but is not routed to the
    liveness endpoint: the router answers it with a redirect whose ``Location``
    is built from the very ``Host`` header this guard exists to distrust.

    Host names are lowercased before Starlette matches them because DNS names
    are case-insensitive. The optional port stays intact for redirects and URL
    generation; TrustedHostMiddleware deliberately ignores it while matching.
    """

    def __init__(
        self,
        app: ASGIApp,
        *,
        allowed_hosts: Iterable[str],
        exempt_paths: Iterable[str],
    ) -> None:
        """Guard ``app`` with ``allowed_hosts`` on every path but ``exempt_paths``."""
        self.app = app
        self.exempt_paths = frozenset(exempt_paths)
        self.guarded_app = TrustedHostMiddleware(app, allowed_hosts=list(allowed_hosts))

    @staticmethod
    def _normalized_host_scope(scope: Scope) -> Scope:
        """Return a scope whose Host name is lowercase, preserving its port."""
        if scope["type"] not in ("http", "websocket"):
            return scope
        authority = Headers(scope=scope).get("host", "")
        hostname, separator, port = authority.partition(":")
        normalized = hostname.lower() + separator + port
        if normalized == authority:
            return scope
        normalized_scope = {**scope, "headers": list(scope["headers"])}
        MutableHeaders(scope=normalized_scope)["host"] = normalized
        return normalized_scope

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] == "http" and get_route_path(scope) in self.exempt_paths:
            await self.app(scope, receive, send)
            return
        await self.guarded_app(self._normalized_host_scope(scope), receive, send)


def _declared_body_length(headers: Headers) -> int | None:
    """Return the declared ``Content-Length``, or ``None`` if there is no usable one."""
    declared = headers.get("content-length")
    # RFC 9110 spells Content-Length `1*DIGIT`. Matching that exactly, rather
    # than deferring to int(), which also accepts "+1", " 1 " and "1_000" -
    # forms no HTTP parser produces and none of which should be read as a size.
    if declared is None or not (declared.isascii() and declared.isdigit()):
        return None
    return int(declared)


class BodySizeLimitMiddleware:
    """
    Reject request bodies that exceed an application-level byte limit.

    Declared sizes are rejected before routing; streamed bodies are counted as
    the downstream endpoint consumes them. A reverse proxy should enforce the
    same limit to cover streams sent to endpoints that never read a body.

    The two rejection paths deliberately produce the same JSON error shape.
    The pre-routing path sends its response by hand, because no framework has
    seen the request yet. The streaming path raises HTTPException instead:
    the raise happens inside the app's own receive() call - i.e. inside the
    endpoint's body read, within the framework's exception handling - so the
    413 comes out shaped like any other FastAPI error (a 422, say) even
    though this wrapper sits outside the framework stack.
    """

    def __init__(self, app: ASGIApp, *, max_body_bytes: int) -> None:
        """Wrap ``app`` with a maximum request-body size."""
        self.app = app
        self.max_body_bytes = max_body_bytes

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] != "http":
            await self.app(scope, receive, send)
            return

        # None when the request declares no length *or* declares one that is
        # not a size - framing is the server's job, the cap is this wrapper's,
        # and the streaming counter below enforces it on whatever actually
        # arrives either way. See "Request body cap" in docs/ARCHITECTURE.md.
        declared = _declared_body_length(Headers(scope=scope))
        if declared is not None and declared > self.max_body_bytes:
            # Hand-rolled, so the {"detail": ...} shape must mirror FastAPI's
            # error responses by convention - tests/test_api.py asserts it.
            response = JSONResponse(
                {"detail": f"Request body exceeds {self.max_body_bytes} bytes"},
                status_code=413,
            )
            await response(scope, receive, send)
            return

        received = 0

        async def guarded_receive() -> Message:
            nonlocal received
            message = await receive()
            if message["type"] == "http.request":
                received += len(message.get("body", b""))
                if received > self.max_body_bytes:
                    raise StarletteHTTPException(
                        413,
                        detail=f"Request body exceeds {self.max_body_bytes} bytes",
                    )
            return message

        await self.app(scope, guarded_receive, send)
